databases:
  db1: "unused_data_out_already_exists"
  db2: "unused_data_out_already_exists"
  lines: 1

datasets:
  points_per_state: 512
  mask_points: false
  seed: 42
  canonical_frame: false
  data_out: "/local/scratch/groves/forge-genie/forge-net/forge_net/data/datasets/slab_generated/slab_dataset.npz"

network:
  arch: "small"
  loss: "mse"
  batch_size: 512
  latent_size: 512
  action_features: ["steps", "positions", "rotations"]
  action_dims: 3
  gradient_clip: 1.0
  optimizer:
    base_learning_rate: 5.0e-4
    min_learning_rate: 1.0e-5
    weight_decay: 1.0e-2
  dropout: 0.1
  use_gpu: true

run:
  run_name: "slab_raw3d_v1_dryrun"
  save_every: 1
  run_folder: ???
  early_stop: False
  patience: 250
  min_delta: 1.0e-6
  num_epochs: 1

eval:
  eval_idxs: [1, 25, 115]
