databases:
  db1: "/local/scratch/groves/jax-forgerl/models/forging_autoencoder/data/databases/noisy_cogging.db"
  db2: "/local/scratch/groves/jax-forgerl/models/forging_autoencoder/data/databases/random_hits.db"
  lines: 10_000 #number of lines in database to read

datasets:
  points_per_state: 512 #number of points to sample per mesh in the database
  use_domain_decomp: true #if uses masking to "focus" point cloud \near boundary condtion (plastic deformation domain)
  use_spatial_features: false
  data_out: "/local/scratch/groves/jax-forgerl/models/forging_autoencoder/data/datasets/test_comb_for_large_512.npz" #user provided path where to save the data

network:
  model_type: "resnetpointae"
  batch_size: 512
  latent_size: 512
  action_features: ["steps", "positions", "rotations"]
  action_dims: 3
  gradient_clip: 1.0
  output_path: "/local/scratch/groves/jax-forgerl/models/forging_autoencoder/model/output_cogging"
  best_model_path: ""
  final_model_path: ""
  optimizer:
    base_learning_rate: 5.0e-4
    min_learning_rate: 1.0e-5
    weight_decay: 1e-2
  scheduler:
    start_factor: 1.0
    end_factor: 0.05
    lr_decay_rate: 1e-3
    lr_decay_step: 1
  dropout: 0.1
  use_gpu: true

run:
  save_every: 50  # match your existing code
  best_model_path: "best_model.pth"
  output_folder: ???
  # early stopping
  early_stop: False
  patience: 250
  min_delta: 1e-6


